logger:
    file:
      path: /open5gs/install/var/log/open5gs/smf.log

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: 1024
  parameter:
      no_ipv4v6_local_addr_in_packet_filter: true

smf:
    freeDiameter: /open5gs/install/etc/freeDiameter/smf.conf
    ctf: 
	    enabled: yes # auto(default)|yes|no
    gtpc:
      server:
        - address: 192.168.250.7
    gtpu:
      server:
        - address: 192.168.250.7
    pfcp:
      server:
        - address: 192.168.250.7
      client:
        upf:
          - address: 192.168.250.8
    session:
      - subnet: 10.100.0.0/16
        gateway: 10.100.0.1
        dnn: internet
      - subnet: 2001:230:cafe::/48
        gateway: 2001:230:cafe::1
        dnn: internet
      - subnet: 192.168.101.0/24
        gateway: 192.168.101.1
        dnn: ims
      - subnet: 2001:230:babe::/48
        gateway: 2001:230:babe::1
        dnn: ims
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    p-cscf:
      - 192.168.250.21
    mtu: 1450
    metrics:
      server:
        - address: 192.168.250.7
          port: 9091

